default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username
  password: password
  host: <%= ENV['IP'] %>
  

develpment: 
  <<: *default
  database: animal-report_development

test:
  <<: *default
  database: animal-report_test

production:
  <<: *default
  database: animal-report_production
  